config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  root 'welcome#index'

  resources :farms, only: [:show, :new, :create, :edit, :update]
  get "/farms/:id/followers" => "farms#followers"
  get "/search" => "farms#search"

  resources :links, only: [:destroy, :create, :edit, :update]
  resources :comments, only: [:destroy, :create]
  resources :ratings, only: [:create]
  resources :connections, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :posts, only: [:show, :create, :edit, :update, :destroy, :new]
 
end

app/models/farm.rb
# == Schema Information
#
# Table name: farms
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  description   :text
#  address       :string(255)
#  latitude      :float
#  longitude     :float
#  hours_open    :string(255)
#  days_open     :string(255)
#  months_open   :string(255)
#  phone_num     :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  user_id       :integer
#  email_address :string(255)
#  payment_types :string(255)
#  offer_spring  :string(255)
#  offer_summer  :string(255)
#  offer_fall    :string(255)
#  offer_winter  :string(255)
#

class Farm < ActiveRecord::Base

	belongs_to :user
	has_many :links
	has_many :comments
	has_many :ratings, as: :rateable
	has_many :connections
	has_many :posts

	validates_presence_of :name, :description, :address, :hours_open, :days_open, :months_open, :phone_num, :payment_types

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
	before_action :authenticate_user!, :except => [:show, :search]

	#GET "/farms/:id"
	def show
		@farm = Farm.find(params[:id])
		
		#sets up hash for map marker
		@hash = Gmaps4rails.build_markers(@farm) do |farm, marker|
		  marker.lat farm.latitude
		  marker.lng farm.longitude
		  marker.infowindow "<a target='blank' href='https://www.google.com/maps/place/"+"#{farm.address}"+"'>Get Directions With Google Maps</a>"
		  marker.json({ title: farm.name })
		end

		@links = @farm.links
		@comments = @farm.comments
		@rating = Rating.where(rateable_type: "Farm", rateable_id: @farm.id)
		@rating_num = @rating.length
		if @rating.blank?
			@rating_average = "0.0"
		else
			@rating_average = @rating.average(:rate_value).round(2)
		end
		if current_user
			@connection = Connection.where(user_id: current_user.id, farm_id: @farm.id)
		end
	end

	#GET "/farms/:id/followers"
	def followers
		@farm = Farm.find(params[:id])
		if is_owner(@farm)
			@connections = @farm.connections
		else
			gflash notice: "You don't have permission to go there."
			redirect_to farm_path(@farm)
		end
	end

	#GET "/farms/:id/edit"
	def edit
		@farm = Farm.find(params[:id])
		if is_owner(@farm)	
			@links = @farm.links
		else
			gflash notice: "You don't have permission to go there."
			redirect_to farm_path(@farm)
		end
	end

	#PUT/PATCH "/farms/:id"
	def update
		@farm = Farm.find(params[:id])
		if is_owner(@farm)
			if @farm.update_attributes(farm_params)
				gflash notice: "#{@farm.name} updated successfully."
				redirect_to farm_path(@farm)
			else
				gflash notice: "Error updating farm."
				render edit_farm_path(@farm) 
			end
		else 
			gflash notice: "You don't have permission to go there."
			redirect_to farm_path(@farm)
		end
	end

	# GET "/farms/new" 
	def new
		@farm = Farm.new
	end

	# POST "/farms"
	def create
		@farm = Farm.new(farm_params)
		@farm.user_id = current_user.id
		if @farm.save
			gflash notice: "Welcome to the family! We are glad you've chosen us to help represent your farm."
			redirect_to farm_path(@farm)
		else
			gflash :now, notice: "There was an error adding your farm. Please make sure you filled everything out."
			render :new
		end
	end

	# GET "/farms/search"
	def search
		@location = params[:search]
		@distance = params[:miles]
		@farms = Farm.near(@location, @distance)

		if @location.empty?
			gflash notice: "You can't search without a search term; please enter a location and retry!"
			redirect_to "/"
		else
			if @farms.length < 1
				gflash notice: "Sorry! We couldn't find any farms within #{@distance} miles of #{@location}."
				redirect_to "/"
			else
				search_map(@farms)
			end
		end

	end

	def blog

	end

	private

	# sets up the map hash for gmaps4rails
	def search_map(farms)
		@farms = farms
		@hash = Gmaps4rails.build_markers(@farms) do |farm, marker|
			  marker.lat farm.latitude
			  marker.lng farm.longitude
			  marker.infowindow "<a href='/farms/"+"#{farm.id}"+"'>#{farm.name}, #{farm.address}</a>"
			  marker.json({ title: farm.name, id: farm.id })
			end
		end

	def is_owner(farm)
		@farm = farm
		if current_user.id == @farm.user_id
			return true
		else
			return false
		end
	end
	
	def farm_params
		params.require(:farm).permit!
	end

end

app/helpers/farms_helper.rb
module FarmsHelper



end

app/views/farms/_farm_comments.html.haml
- if @comments.empty?
	= "Be the first to leave a comment!"
	- if current_user == nil
		= link_to "Sign Up", "/users/sign_up", method: "get"
		= "/"
		= link_to "Sign In", "/users/sign_in", method: "get"
- else
	- @comments.each do |c|
		%strong= "#{c.user.name}: " if c.user 
		= c.content.to_s
		- if current_user
			- if current_user.id == c.user_id
				= link_to "Delete", comment_path(c), method: "delete"
		%br

	- if current_user == nil
		= "Join the conversation!"
		= link_to "Sign Up", "/users/sign_up", method: "get"
		= "/"
		= link_to "Sign In", "/users/sign_in", method: "get"
%br

- if current_user
	%h2 Add A Comment
	= form_for Comment.new, url: "/comments", method: :post do |f|
		= f.hidden_field :farm_id, value: @farm.id
		= f.text_area :content, class: "form-control"
		%br
		= f.submit "Add Comment", :class => "btn btn-success btn-block"

app/views/farms/_farm_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { mapTypeId: google.maps.MapTypeId.HYBRID }, 
	internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(16);
});
</script>

app/views/farms/_follow_farm.html.haml
%br
= form_for Connection.new, url: "/connections", method: :post do |c|
	= c.hidden_field :farm_id, value: @farm.id
	= c.hidden_field :user_id, value: current_user.id if current_user
	= c.submit "Follow this Farm!", :class => "btn btn-success", :data => { :confirm => 'By following this farm you agree to recieve emails from them occasionally.' }

app/views/farms/_form.html.haml
= f.label "What is the name of your farm?"
%br 
= "This is the title that will be shown for your farm"
%br
= f.text_field :name, class: "form-control"
%br
= f.label "Tell us about your farm."
%br
= "Let people know who you are and why you do what you do. Tell them a short story." 
%br
= "(Try for 200-250 words.)"
%br
= f.text_area :description, class: "form-control"
%br
= f.label "What do you offer in the spring?"
%br
= "March, April, May (if nothing, leave blank)"
%br
= "example: strawberries, corn, radishes"
%br
= f.text_area :offer_spring, class: "form-control"
%br
= f.label "What do you offer in the summer?"
%br
= "June, July, August (if nothing, leave blank)"
%br
= "example: corn, peaches, greens"
%br
= f.text_area :offer_summer, class: "form-control"
%br
= f.label "What do you offer in the fall?"
%br
= "September, October, November (if nothing, leave blank)"
%br
= "example: pumpkins, corn-maze, hay-rides"
%br
= f.text_area :offer_fall, class: "form-control"
%br
= f.label "What do you offer in the winter?"
%br
= "December, January, February (if nothing, leave blank)"
%br
= "example: christmas trees, sleigh-rides, turkeys"
%br
= f.text_area :offer_winter, class: "form-control"
%br
= f.label "What is the address of the farm?"
%br
= "format: 1234 Some Road, City, State 10099"
%br
= f.text_field :address, class: "form-control"
%br
= f.label "What are your normal hours?"
%br
= "(example: 8 a.m. till 5 p.m.)"
%br
= f.text_field :hours_open, class: "form-control"
%br
= f.label "What days are you open?"
%br
= "(example: Mon - Fri)"
%br
= f.text_field :days_open, class: "form-control"
%br
= f.label "What months are you open?"
%br
= "(example: May, June, July, Year Round)"
%br
= f.text_field :months_open, class: "form-control"
%br
= f.label "What forms of payment do you accept?"
%br
= "(cash, credit, check, dish washing)"
%br
= f.text_field :payment_types, class: "form-control"
%br
= f.label "Farm Phone Number"
%br
= "format: (000)-000-0000"
%br
= f.telephone_field :phone_num, class: "form-control"
%br
= f.label "Farm Email Address"
%br
= "Use a valid email. Customers will contact you this way and it is also how you will be notified of comments on your farm."
%br
= f.email_field :email_address, class: "form-control"

app/views/farms/_rating_form.html.haml
%h2 Add A Rating
= form_for Rating.new, url: "/ratings", method: :post do |r|
	= r.hidden_field :rateable_id, value: @farm.id
	= r.hidden_field :rateable_type, value: "Farm"
	%i= "Have you visited this farm?"
	%br
	= r.label "Yes"
	= r.radio_button :has_visited, true
	%br
	= r.label "No"
	= r.radio_button :has_visited, false
	%br
	= r.label "Select a Rating 1 being bad and 10 being really great!"
	%br
	= r.select :rate_value, options_for_select(1..10)
	%br
	%br
	= r.submit "Add Rating", :class => "btn btn-success btn-block"
%br
%br

app/views/farms/_ratings_form.html.haml
- if @rating.present?
	%i= "Rated from 1 to 10"
	%br
	%strong{class: "big_rating"}= @rating_average
	%br
	%i= "Rated by #{@rating_num} people."
	%br
	- if current_user == nil
		= "Want to rate this farm?"
		= link_to "Sign Up", "/users/sign_up", method: "get"
		= "/"
		= link_to "Sign In", "/users/sign_in", method: "get"
- else
	= "No one has rated this farm yet."
	- if current_user == nil
		= "Want to rate this farm?"
		= link_to "Sign Up", "/users/sign_up", method: "get"
		= "/"
		= link_to "Sign In", "/users/sign_in", method: "get"

- if current_user
	- if has_rated(current_user, @farm) == false
		= render "rating_form"	
	- else
		%i= "You've already rated this farm."

app/views/farms/_search_map.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { mapTypeId: google.maps.MapTypeId.HYBRID, maxZoom: 16 }, 
	internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/farms/edit.html.haml
.col-md-6.col-md-offset-3
	%br
	= button_to "Go Back to Farm", farm_path(@farm), method: "get", class: "btn btn-success btn-block"

	%h1 Edit This Farm

	= form_for @farm do |f|
		= render "form", f: f
		%br
		= f.submit "Update Your Farm", class: "btn btn-success btn-lg btn-block"
	%br
	%br

	%h2 Add Links To This Farm
	= "If you've made updates above, go ahead and update the farm before adding links."

	%h3 Current Links
	%table{:class => "table table-striped table-hover"}
		%thead
			%th Link Name
			%th Link URL
			%th Edit / Delete
		%tbody
			- @links.each do |l|
				%tr
					%td= l.name
					%td= l.url
					%td
						= link_to "Edit Link", edit_link_path(l)
						="/"
						= link_to "Delete Link", link_path(l), method: "delete"
		

	%br
	%button{id: "farm_link_button", class: "btn btn-warning btn-lg btn-block"}
		Add Link to this Farm

.mod_overlay{:id => "mod_overlay"}
.add_new_link{:id => "add_new_link"}
	.add_new_link_inside{:id => "add_new_link_inside"}
		%h3 Add A Link to this Farm
		= form_for Link.new do |l|
			= l.hidden_field :farm_id, value: @farm.id
			= l.label "Link Name"
			%br
			= "example: twitter, facebook, website"
			%br
			= l.text_field :name, class: "form-control"
			%br
			= l.label "Full URL"
			%br
			= "example: https://www.facebook.com/yourpage"
			%br
			= l.text_field :url, class: "form-control"
			%br
			= l.submit "Add Link", class: "btn btn-info btn-lg btn-block"
			%br
		%button.btn.btn-default.btn-lg.btn-block{:id => "close_new_q_modal"}
			Close

app/views/farms/followers.html.haml
.col-md-8.col-md-offset-2
	%br
	= button_to "Go Back to Farm", farm_path(@farm), method: "get", class: "btn btn-success btn-block"
	%h1 All Users Who Follow You
	%table{:class => "table table-striped table-hover"}
		%thead
			%th Name
			%th Email
			%th Delete Connection
		%tbody
			- @connections.each do |f|
				%tr
					%td= f.user.name
					%td 
						= mail_to f.user.email
					%td
						= link_to "Remove Follower", connection_path(f), method: :delete

	%h2 Contact List
	- @connections.each do |e|
		= "#{e.user.email}, "

app/views/farms/new.html.haml
.col-md-6.col-md-offset-3
	%h1 Add A New Farm!

	= form_for @farm do |f|
		= render "form", f: f
		%br
		= f.submit "Add Your Farm", class: "btn btn-success btn-lg btn-block"
	%br
	%br

app/views/farms/search.html.haml
%div{style: "width:100%;"}
	#map{style: "width: 100%; height: 500px;"}
		= render "search_map"

.col-md-10.col-md-offset-1			
	%h2= "Farms Near: #{params[:search].titleize}"
	%table{:class => "table table-striped table-hover"}
		%thead
			%th Name
			%th Address
			%th Days Open
			%th Hours Open
			%th Phone Number
			%th Distance
		%tbody
			- @farms.each do |f|
				%tr
					%td
						= link_to f.name, farm_path(f), method: "get"
					%td= f.address
					%td= f.days_open
					%td= f.hours_open
					%td= f.phone_num
					%td
						%strong= f.distance.round(2)
						= "miles"

app/views/farms/show.html.haml
%div{style: "width:100%;"}
	#map{style: "width: 100%; height: 300px;"}
		= render "farm_map"

.col-md-8.col-md-offset-2
	.directions_div
		%br
		= link_to "Get Directions", "https://www.google.com/maps/place/#{@farm.address}", :target => "_blank"
		%br
		- if current_user
			- if has_connected(current_user, @farm)
				= link_to "Quit Following This Farm", connection_path(@connection.first), method: :delete
			- else
				= render "follow_farm"
	
	%h1= @farm.name

.col-md-6.col-md-offset-2	
	
	%h4= "Who We Are and What We Do"
	%br
	= simple_format(@farm.description)
	%h3= "What We Offer"
	.col-md-3.col-sm-6
		%h4= "Spring"
		- if @farm.offer_spring.blank?
			%strong= "Nothing"
		- else 
			%strong= @farm.offer_spring
	.col-md-3.col-sm-6
		%h4= "Summer"
		- if @farm.offer_summer.blank?
			%strong= "Nothing"
		- else 
			%strong= @farm.offer_summer
	.col-md-3.col-sm-6
		%h4= "Fall"
		- if @farm.offer_fall.blank?
			%strong= "Nothing"
		- else 
			%strong= @farm.offer_fall
	.col-md-3.col-sm-6
		%h4= "Winter"
		- if @farm.offer_winter.blank?
			%strong= "Nothing"
		- else 
			%strong= @farm.offer_winter

	.clearfix
	%h2 Comments
	= render "farm_comments"
	

.col-md-2
	%h3= "General Info"
	- if @links.present?
		%h4= "Find Us Elsewhere"
		- @links.each do |l|
			= link_to l.name, l.url, target: "_blank"
	%h4= "Address"
	= @farm.address
	%h4= "Hours Open"
	= @farm.hours_open
	%br
	%h4= "Days Open"
	= @farm.days_open
	%br
	%h4= "Months Open"
	= @farm.months_open
	%br
	%h4= "Payment Types"
	= @farm.payment_types
	%br
	%h4= "Phone"
	= @farm.phone_num
	%br
	%h4= "Email"
	= mail_to @farm.email_address
	%h3 User Ratings
	= render "ratings_form"


- if current_user	
	- if current_user.id == @farm.user_id
		.edit_farm_button{id: "edit_farm_button"}
			= button_to "Edit this Farm", edit_farm_path(@farm), method: "get", class: "btn btn-warning"
			= button_to "Your Followers", "/farms/#{@farm.id}/followers", method: "get", class: "btn btn-warning"
			