config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  root 'welcome#index'

  resources :farms, only: [:show, :new, :create, :edit, :update]
  get "/farms/:id/followers" => "farms#followers"
  get "/search" => "farms#search"

  resources :links, only: [:destroy, :create, :edit, :update]
  resources :comments, only: [:destroy, :create]
  resources :ratings, only: [:create]
  resources :connections, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :posts, only: [:show, :create, :edit, :update, :destroy, :new]
 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  email              :string(255)      default(""), not null
#  encrypted_password :string(255)      default(""), not null
#  sign_in_count      :integer          default(0), not null
#  current_sign_in_at :datetime
#  last_sign_in_at    :datetime
#  current_sign_in_ip :string(255)
#  last_sign_in_ip    :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  name               :string(255)
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :farms
  has_many :comments
  has_many :connections
  
  devise :database_authenticatable, :registerable, :trackable, :validatable
  validates_presence_of :name
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	#GET "/users/:id" 
	def show
		@user = User.find(params[:id])
		@farms = @user.farms
		@connections = @user.connections
	end

end

app/views/users/show.html.haml
.col-md-10.col-md-offset-1
	%h1 Your Farms & Connections

	- if @farms.length >= 1
		%h2 Farms You Manage
		%table{:class => "table table-striped table-hover"}
			%thead
				%th Name
				%th Address
				%th Days Open
				%th Hours Open
				%th Phone Number
			%tbody
				- @farms.each do |f|
					%tr
						%td
							= link_to f.name, farm_path(f), method: "get"
						%td= f.address
						%td= f.days_open
						%td= f.hours_open
						%td= f.phone_num

	- if @connections.length >= 1
		%h2 Farms You Follow
		- @connections.each do |f|
			.col-md-4.col-sm-6
				.farm_sum
					.button_div.first_button
						%h4= link_to f.farm.name.truncate(60), farm_path(f.farm), method: "get"
						%br
						%strong= "Address: "
						= f.farm.address.truncate(30)
						%br
						%strong= "Days Open: "
						= f.farm.days_open
						%br
						%strong= "Hours: "
						= f.farm.hours_open
						%br
						%strong= "Phone: "
						= f.farm.phone_num
						%br
						%strong= "Description: "
						= f.farm.description.truncate(110)
						%br
						.ey_nav_div
							= link_to "Quit Following This Farm", connection_path(f), method: :delete
					.button_div.real_button_div
						= button_to "View Farm", farm_path(f.farm), method: "get", class: "btn btn-info btn-block"



			/ %tr
			/ 	%td
			/ 		= link_to f.farm.name, farm_path(f.farm), method: "get"
			/ 	%td= f.farm.address
			/ 	%td= f.farm.days_open
			/ 	%td= f.farm.hours_open
			/ 	%td= f.farm.phone_num
			/ 	%td
			/ 		= link_to "Quit Following", connection_path(f), method: :delete
	- else
		%h2 You Haven't Followed any Farms Yet